// frontend/src/components/post/Post.tsx
import React from 'react';
import { useState ,useEffect } from 'react';
import { useNavigate } from "react-router-dom";


import Comments from '../comments/Comments';
import './post.css';
import { Question } from '../../models/Question';
import { Answer } from '../../models/Answer';
import likeService from '../../services/likeService';
import { LikeRequest } from '../../models/LikeRequest';


interface PostProps{
    question : Question;
    answer : Answer;
    isFeed : boolean;
}

export default function Post({question,answer, isFeed} : PostProps) {

    const filledHeartUrl = 'assets/filled_heart.png';
    const emptyHeartUrl = 'assets/empty_heart.png'; 
    const username = answer.userEmail.split('@')[0];
    let areCommentsVisible : boolean = false;
    const [likes,setLikes] = useState(0);
    const [likeIconUrl,setLikeIconUrl] = useState(emptyHeartUrl);
    const navigate = useNavigate();
    
    

    function navigateToQuestionDetailFeed(question : Question){
        console.log('navigating', question);
        navigate('questionDetails',{state : question});
    }

    useEffect(() => {
        if(answer.likes != null && answer.likes.length > 0 ){
            setLikes(answer.likes.length);
            if(answer.likes.filter(like => (like.answerId == answer.answerId && like.userEmail == 'shivateja.bandaru@gmail.com')).length > 0 ){
                setLikeIconUrl(filledHeartUrl);
            }
        }
    },[answer.answerId,answer.likes]);

    function toggleLike(){
        likeIconUrl === emptyHeartUrl ? setLikeIconUrl(filledHeartUrl) : setLikeIconUrl(emptyHeartUrl);;
        likeIconUrl === emptyHeartUrl ? dislikeAnswer() : likeAnswer();
    }

    function likeAnswer(){
        let likeRequest = new LikeRequest(answer.answerId,"shivateja.bandaru@gmail.com");
        likeService.likeAnswer('',likeRequest)
        .then(response => setLikes(likes +1) )
        .catch(error => console.log("Sorry like  Failed"));
    }

    function dislikeAnswer(){
        likeService.dislikeAnswer('',1)
        .then(response => setLikes(likes - 1))
        .catch(error => console.log("Sorry dislike Failed"));
    }

    function toggleCommentsVisibility(){
        areCommentsVisible = !areCommentsVisible;
    }

    return (
        <div className='post'>
        <div className="postWrapper">
        <div className="postTop">
            <div className="postTopLeft">
                <img className='postProfileImg'
                src="assets/persons/shiva.jpg" 
                alt="" />
                <span className="postUsername">
                    {username}
                </span>
                <span className="postDate">{answer.timestamp}</span>
            </div>
        </div>
        <div className="postCenter">
           {isFeed && <a  onClick={() => navigateToQuestionDetailFeed(question)}> <strong>{question.questionContent}</strong></a> }
            <p></p>
            <span className="postText">{answer.answerContent}</span>
        </div>
        <div className="postBottom">
            <div className="postBottomLeft">
            <img className='likeIcon' src={likeIconUrl}  alt="" onClick={toggleLike}/>
            <span className="postLikeCounter">{likes}</span>
            </div> 
            <div className="postBottomRight">
            <span className="postCommenttext" onClick={toggleCommentsVisibility}>comments</span>
            </div>
        </div>
        {areCommentsVisible && <Comments comments = {answer.comments}/>}
    </div>
    </div>
    )
}

// src/app/shared/post/post.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Comment } from '../comment.model';
import { LikesService } from '../likes.service';
import { Like as LikeModel } from '../like.model';
import { Like } from '../like';

@Component({
  selector: 'post',
  templateUrl: './post.component.html',
  styleUrls: ['./post.component.css']
})
export class PostComponent implements OnInit {

  @Input() questionId: number = 0;

  @Input() answerId: number = 0;

  @Input() questionContent: string = '';

  @Input() answerContent: string = '';

  @Input() timestamp: string = '';

  @Input() userEmail: string = '';

  @Input() comments: Comment[] = [];

  likes: LikeModel[] = [];

  commentsCount : number =0 ;

  commentsVisible: boolean = false;

  questionDetailRoutePath: string = '/question';

  questionDetails: any = {};

  likeIconPath : string = '';

  emptyHeartIconPath : string = '/assets/empty_heart.png';

  filledHeartIconPath : string = '/assets/filled_heart.png';

  currentUserLikeObject : LikeModel | null = null;

  constructor(private likesService : LikesService) { }

  ngOnInit(): void {
    this.questionDetails = { 
      questionId : this.questionId,
      questionContent : this.questionContent
    };
    this.commentsCount = this.comments.length;
    this.loadLikes();
  }

  toggleCommentsVisibility() {
    this.commentsVisible = !this.commentsVisible
  }

  incrementCommentCount(){
    this.commentsCount++;
  }

  decrementCommentCount(){
    this.commentsCount--;
  }

  toggleLike(){
    if(this.likeIconPath == this.filledHeartIconPath){
      this.dislikeAnswer();
    }
    else if(this.likeIconPath == this.emptyHeartIconPath){
      this.likeAnswer();
    }
  }

  private likeAnswer(){
    this.likeIconPath = this.filledHeartIconPath;
    let like  = new Like(this.answerId,'shivateja.bandaru@gmail.com');
    this.likesService.likeAnswer(like).subscribe(res => {
      this.loadLikes();
    });
  }

  private dislikeAnswer(){
      this.likesService.disLikeAnswer(this.currentUserLikeObject!.likeId).subscribe(res => {
        this.loadLikes();
    });
  }

  private loadLikes(){
    this.likesService.getLikes().subscribe((likes)=>{
      this.likes = likes.filter(like => like.answerId == this.answerId);
      this.getCurrentUserLikeObject();
      this.likeIconPath = this.currentUserLikeObject != null ? this.filledHeartIconPath : this.emptyHeartIconPath;
    });
  }

  private getCurrentUserLikeObject(){
    const currentUserLikes = this.likes.filter(like => like.userEmail == 'shivateja.bandaru@gmail.com');
    if(currentUserLikes != null && currentUserLikes.length > 0){
      this.currentUserLikeObject = currentUserLikes[0];
    }
    else{
      this.currentUserLikeObject = null;
    }
  }
}

<div class='post'>
    <div class="postWrapper">
      <div class="postTop">
          <div class="postTopLeft">
              <img class='postProfileImg'
               src="assets/persons/shiva.jpg" 
              alt="" />
              <span class="postUsername">
                {{userEmail}}
                </span>
              <span class="postDate">{{timestamp}}</span>
          </div>
      </div>
      <div class="postCenter">
        <strong><a [routerLink]="questionDetailRoutePath" [queryParams]="questionDetails">{{questionContent}}</a></strong>
        <br>
        <span class="postText">{{answerContent}}</span>
      </div>
      <div class="postBottom">
        <div class="postBottomLeft">
          <img class='likeIcon' (click)="toggleLike()" src={{likeIconPath}}  alt="" />
          <span class="postLikeCounter"> {{likes.length}} likes</span>
        </div> 
        <div class="postBottomRight">
          <span class="postCommenttext" (click)="toggleCommentsVisibility()">{{commentsCount}} comments</span>
        </div>
      </div>
      <comments *ngIf="commentsVisible" [answerId]="answerId" (commentPostedEvent)="incrementCommentCount()"></comments>
  </div>
</div>
