// frontend/src/components/topbar/Topbar.tsx
import React from 'react'
import { Person, Chat, Notifications } from "@mui/icons-material";
import SearchIcon from '@mui/icons-material/Search';
import "./topbar.css"

export default function Topbar(){
    return (
        <div className="topbarContainer">
            <div className="topbarLeft">
                <a className="logo">Askme</a>
            </div>
            <div className="topbarCentre">
                {/*<div className="searchbar">
                    <SearchIcon/>
                    <input placeholder="Search for questions , spaces or any user" className="searchInput" />
                    </div> */}
            </div>
            <div className="topbarRight">
                <div className="topbarLinks">
                    <span className="topbarLink">Home Page</span>
                    <span className="topbarLink">Timeline</span>
                </div>
                <div className="topbarIcons">
                    <div className="topbarIconItem">
                        <Person />
                        <span className="topbarIconBadge">1</span>
                    </div>
                    <div className="topbarIconItem">
                        <Chat/>
                        <span className="topbarIconBadge">2</span>
                    </div>
                    <div className="topbarIconItem">
                        <Notifications/>
                        <span className="topbarIconBadge">1</span>
                    </div>
                </div>
                <img src="assets/dp.png" alt="" className="topbarImg" />
            </div>
        </div>
    )
}

// src/app/shared/topbar/topbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'topbar',
  templateUrl: './topbar.component.html',
  styleUrls: ['./topbar.component.css']
})
export class TopbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="topbarContainer">
    <div class="topbarLeft">
        <a class="logo" routerLink="">Askme</a>
    </div>
    <div class="topbarCentre">
        <div class="searchbar">
            <mat-icon>search</mat-icon>
            <input placeholder="Search for questions , spaces or any user" class="searchInput" />
        </div>
    </div>
    <div class="topbarRight">
        <div class="topbarLinks">
            <span class="topbarLink">Home Page</span>
            <span class="topbarLink">Timeline</span>
        </div>
        <div class="topbarIcons">
            <div class="topbarIconItem">
                <mat-icon>person</mat-icon>
                <span class="topbarIconBadge">1</span>
            </div>
            <div class="topbarIconItem">
                <mat-icon>chat</mat-icon>
                <span class="topbarIconBadge">2</span>
            </div>
            <div class="topbarIconItem">
                <mat-icon>notifications</mat-icon>
                <span class="topbarIconBadge">1</span>
            </div>
        </div>
        <img src="assets/persons/shiva.jpg" alt="" class="topbarImg" />
    </div>
</div>
