// frontend/src/components/modal/Modal.tsx
import React,{useState} from 'react';
import './modal.css';
import { Question } from '../../models/Question';

interface ModalProp{
    question : Question;
    toggleModalState : () => void;
}

export default function Modal({question, toggleModalState} : ModalProp){

    const rows = 20;
    const columns = 70;

    const [answerContent,setAnswerContent] = useState('');

    const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        const  value  = e.target.value;
        setAnswerContent(value);
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if(answerContent !=null && answerContent.length > 0){
            console.log('the answer posted is: '+answerContent);
            toggleModalState();
        }
    };

    return (
        <div className="modal">
            <div className="modal-content">
            <button id="closeButton" onClick={toggleModalState}>X</button>
            <form onSubmit={handleSubmit}>
                <h2>{question.questionContent}</h2>
                <textarea rows={rows} cols={columns} placeholder="Write your answer" onChange={handleChange}></textarea>
                <button id='postButton'>Post Answer</button>
            </form>
            </div>
        </div>
    )
}

// src/app/shared/modal/modal.component.ts
import { Component, OnInit ,EventEmitter , Output , Input} from '@angular/core';
import { FormControl } from '@angular/forms';
import { AnswersService } from '../answers.service';
import { Answer } from '../answer';
import { NotifyAnswerService } from '../notify-answer.service';

@Component({
  selector: 'app-modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.css']
})
export class ModalComponent {

  @Input() questionTitle = '';
  @Input() questionId : number = 0;
  @Output() closeModalEvent = new EventEmitter<boolean>();
  answerContent = new FormControl('');
  errorMessage : string = '';

  constructor(private answersService : AnswersService,private notifyAnswerService : NotifyAnswerService){}

  closeModal() {
    this.closeModalEvent.emit(true);
  }
  
  postAnswer() : void {

    if(this.answerContent.value == null || this.answerContent.value!.length == 0) {
      this.errorMessage = "Answer cannot be empty";
      return;
    }

    let answer = new Answer(this.answerContent.value!,this.questionId,"shivateja.bandaru@gmail.com");
      console.log("answer to be posted : " + this.questionId + " " + this.answerContent.value);
      this.answersService.postAnswer(answer).subscribe(response => {
        console.log(response);
        this.closeModalEvent.emit(true);
        this.notifyAnswerService.triggerAnswerPosted();
      },error => {
        console.log("An error has occurred" + error);
      });
  }
}

<div class="modal">
    <div class="modal-content">
      <button id="closeButton" (click)="closeModal()">X</button>
      <span>{{errorMessage}}</span>
      <h2>{{questionTitle}}</h2>
      <textarea rows="20" cols="80" placeholder="Write your answer" [formControl]="answerContent"></textarea>
      <button id='postButton' (click)="postAnswer()">Post Answer</button>
    </div>
</div>
