// frontend/src/components/questionForYou/QuestionForYou.tsx
import React from 'react';
import  './questionForYou.css';

export default function QuestionForYou(){
    return (
        <li className="rightbarFriend">
            <div className="rightbarProfileImgContainer">
                <span className="rightbarOnline"></span>
            </div>
            <a className="rightbarUsername">questionContent</a>
        </li>
    )
}

// src/app/shared/question-for-you/question-for-you.component.ts
import { Component, OnInit,Input } from '@angular/core';

@Component({
  selector: 'question-for-you',
  templateUrl: './question-for-you.component.html',
  styleUrls: ['./question-for-you.component.css']
})
export class QuestionForYouComponent implements OnInit {
  @Input() questionContent : string = '';
  constructor() { }

  ngOnInit(): void {
  }

}

<li class="rightbarFriend">
    <div class="rightbarProfileImgContainer">
        <span class="rightbarOnline"></span>
    </div>
    <a class="rightbarUsername">{{questionContent}}</a>
</li>
