// src/app/shared/share/share.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { QuestionsService } from '../questions.service';
import { NotifyPostService } from '../notify-post.service';

@Component({
  selector: 'share',
  templateUrl: './share.component.html',
  styleUrls: ['./share.component.css']
})
export class ShareComponent implements OnInit {

  questionContent = new FormControl('');
  
  constructor(private questionsService : QuestionsService, private notifyPostService : NotifyPostService) { }

  ngOnInit(): void {
  }

  postQuestion() {

    if(this.questionContent.value!.length > 0) {

      let question = {'questionContent' : this.questionContent.value,'userEmail' : 'shivateja.bandaru@gmail.com'};
      this.questionsService.postQuestion(question).subscribe(data => {
        console.log('Question Posted : ' + data);
        this.notifyPostService.triggerQuestionPosted();
      });

      this.questionContent = new FormControl('');

    }

  }
}
<div class='share'>
    <div class="shareWrapper">
      <div class="shareTop">
          <img class='shareProfileImg' src="assets/persons/shiva.jpg" alt="" />
          <input placeholder="Ask a Question" class='shareInput' [formControl]="questionContent"/>
      </div>
      <hr class='shareHr'/>
      <div class="shareBottom">
          <button class='shareButton' (click)="postQuestion()">Post Question</button>
      </div>
    </div>
</div>

// frontend/src/components/share/Share.tsx
import React,{useState} from 'react';
import './share.css'
import questionService from '../../services/questionService';
import { QuestionRequest } from '../../models/QuestionRequest';
import { Question } from '../../models/Question';

export default function Share(){

    const [questionContent,setQuestionContent] = useState({inputValue : ''});

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const  value  = e.target.value;
        setQuestionContent({inputValue : value});
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if(questionContent!=null && questionContent.inputValue.length > 0) {
            const newQuestion = new QuestionRequest(questionContent.inputValue,"shivateja.bandaru@gmail.com");
            questionService.postQuestion('', newQuestion)
            .then((response) => {
                console.log("the question posted is " + response);
                setQuestionContent({inputValue : ''});
            })
            .catch((error) => {
                console.log("question posting failed: " + error);
            });
        }
    };

    return (
        <div data-testid="share-component" className='share'>
            <div className="shareWrapper">
            <form onSubmit={handleSubmit}>
                <div className="shareTop">
                    <img className='shareProfileImg' src="assets/dp.png" alt="" />
                    <input data-testid="shareInput" placeholder="Ask a Question" value={questionContent.inputValue} className='shareInput' onChange={handleChange}/>
                </div>
                <hr className='shareHr'/>
                <div className="shareBottom">
                    <button type ='submit'className='shareButton' >Post Question</button>
                </div>
            </form>
            </div>
        </div>
    )
}
