// src/app/shared/question-title/question-title.component.ts
import { Component, OnInit,Input } from '@angular/core';

@Component({
  selector: 'question-title',
  templateUrl: './question-title.component.html',
  styleUrls: ['./question-title.component.css']
})
export class QuestionTitleComponent implements OnInit {

  @Input() questionTitle : string = '';
  @Input() questionId : number = 0;
  showModal: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  openModal() {
    this.showModal = true;
  }

  closeModal() {
    this.showModal = false;
  }
  
}

<div class='questionTitle'>
    <div class="questionTitleWrapper">
      <div class="questionTitleBottom">
         <strong>{{questionTitle}}</strong>
      </div>
      <br>
      <button class="answerButton" (click)="openModal()">Answer</button>
      <app-modal *ngIf="showModal" (closeModalEvent)="closeModal()" questionTitle={{questionTitle}} [questionId] = "questionId"></app-modal>
    </div>
</div>

// frontend/src/components/questionTitle/QuestionTitle.tsx
import React,{useState} from 'react';
import Modal from '../modal/Modal';
import './questionTitle.css';
import { QuestionProp } from '../../models/QuestionProp';




export default function QuestionTitle({question} : QuestionProp){
    const [modalState,setModalState] = useState(false);

    function toggleModalState(){
        setModalState(!modalState);
    }   

    return (
        <div className='questionTitle'>
            <div className="questionTitleWrapper">
            <div className="questionTitleBottom">
                <strong>{question.questionContent}</strong>
            </div>
            <button className="answerButton" onClick={toggleModalState} >Answer</button>
            {modalState && <Modal question={question} toggleModalState={toggleModalState}/>}
            </div>
        </div>
    )
}
