// frontend/src/pages/home/Home.tsx
import React from 'react';

import Topbar from "../../components/topbar/Topbar";
import Leftbar from "../../components/leftbar/Leftbar";
import Feed from "../../components/feed/Feed";
import Rightbar from "../../components/rightbar/Rightbar";
import "./home.css";

export default function Home(){
    return (
        <>
        <Topbar/>
        <div className="homeContainer">
            <Leftbar/>
            <Feed/>
            <Rightbar/>
        </div>
        </>
    )
}

// src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div>
    <topbar></topbar>
    <div class="homeContainer">
    <leftbar class="leftbarContainer"></leftbar>
    <feed class="feedContainer"></feed>
    <rightbar></rightbar>
    </div>
</div>
